### ISSUE TITLE
💄 Main Page UI

### ISSUE THREAD

**Issue by Valentino1994** [Valentino1994/GitTodo#3]
## Motivation
- I should make a Main Page

## TODO
- [x] Make Dummy Model
- [ ] Repository Cell
- [ ] Issue Cell
- [ ] CollectionView
- [ ] Issue list changing by a repository
- [ ] Issue add modal 
- [ ] Move Button to User Page
- [ ] Move Button to Issue Detail
